# Generated by Django 4.1 on 2022-08-30 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travellers', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=55)),
                ('created_date', models.DateField(verbose_name=datetime.datetime(2022, 8, 30, 5, 26, 31, 309755))),
                ('image', models.ImageField(upload_to='images')),
                ('highlighted_image', models.ImageField(upload_to='highlighted_images')),
                ('travellers', models.ManyToManyField(blank=True, null=True, to='home.traveller')),
            ],
        ),
    ]
