# Generated by Django 4.1 on 2022-08-28 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='created_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 8, 28, 17, 16, 52, 967104)),
        ),
    ]
