# Generated by Django 4.1 on 2022-08-28 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_journey_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='location',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journey',
            name='created_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 8, 28, 20, 36, 41, 248537)),
        ),
    ]
