# Generated by Django 4.1 on 2022-08-28 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_journey_location_alter_journey_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='created_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 8, 28, 20, 39, 34, 494381)),
        ),
    ]
