# Generated by Django 4.1 on 2022-08-28 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_journey_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='created_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 8, 28, 20, 41, 28, 33919)),
        ),
        migrations.AlterField(
            model_name='journey',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
